# This single codebase performs generating of subject, verb, article, adjective, and noun, plus sentence assembly.
# True microservices would have separate codebases, but for our purposes a single codebase is fine.
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=dc lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=marvel lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=dcvsmarvel lab-4-eureka-client-solution-0.0.1-SNAPSHOT.jar

---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: dcvsmarvel
server:
  port: 8020  
heroes: NotApplicable
    
---
spring:
  profiles: dc
heroes: Superman,Mujer Maravilla,Batman,Flash,Linterna Verde
  
---
spring:
  profiles: marvel
heroes: Iron man,Thor,Spiderman,Hulk,Capitan America

  