---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: marvel
words: Iron Man,Spiderman,Ant-man,Hulk,Thor
  
---
spring:
  profiles: dc
words: Batman,Mujer Maravilla,Flash,Linterna Verde,Megamente


  